// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: service_exchange_rate_api.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromCurrency string `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency   string `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
}

func (x *GetRateRequest) Reset() {
	*x = GetRateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_exchange_rate_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateRequest) ProtoMessage() {}

func (x *GetRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_exchange_rate_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateRequest.ProtoReflect.Descriptor instead.
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return file_service_exchange_rate_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *GetRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type GetRateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrencyCodeFrom string               `protobuf:"bytes,2,opt,name=currency_code_from,json=currencyCodeFrom,proto3" json:"currency_code_from,omitempty"`
	CurrencyCodeTo   string               `protobuf:"bytes,3,opt,name=currency_code_to,json=currencyCodeTo,proto3" json:"currency_code_to,omitempty"`
	Buy              float64              `protobuf:"fixed64,4,opt,name=buy,proto3" json:"buy,omitempty"`
	Sell             float64              `protobuf:"fixed64,5,opt,name=sell,proto3" json:"sell,omitempty"`
	ValidateDate     *timestamp.Timestamp `protobuf:"bytes,6,opt,name=validate_date,json=validateDate,proto3" json:"validate_date,omitempty"`
}

func (x *GetRateResponse) Reset() {
	*x = GetRateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_exchange_rate_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateResponse) ProtoMessage() {}

func (x *GetRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_exchange_rate_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateResponse.ProtoReflect.Descriptor instead.
func (*GetRateResponse) Descriptor() ([]byte, []int) {
	return file_service_exchange_rate_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetRateResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRateResponse) GetCurrencyCodeFrom() string {
	if x != nil {
		return x.CurrencyCodeFrom
	}
	return ""
}

func (x *GetRateResponse) GetCurrencyCodeTo() string {
	if x != nil {
		return x.CurrencyCodeTo
	}
	return ""
}

func (x *GetRateResponse) GetBuy() float64 {
	if x != nil {
		return x.Buy
	}
	return 0
}

func (x *GetRateResponse) GetSell() float64 {
	if x != nil {
		return x.Sell
	}
	return 0
}

func (x *GetRateResponse) GetValidateDate() *timestamp.Timestamp {
	if x != nil {
		return x.ValidateDate
	}
	return nil
}

type GetBuyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buy float64 `protobuf:"fixed64,1,opt,name=buy,proto3" json:"buy,omitempty"`
}

func (x *GetBuyResponse) Reset() {
	*x = GetBuyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_exchange_rate_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuyResponse) ProtoMessage() {}

func (x *GetBuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_exchange_rate_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuyResponse.ProtoReflect.Descriptor instead.
func (*GetBuyResponse) Descriptor() ([]byte, []int) {
	return file_service_exchange_rate_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetBuyResponse) GetBuy() float64 {
	if x != nil {
		return x.Buy
	}
	return 0
}

type GetSellResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sell float64 `protobuf:"fixed64,1,opt,name=sell,proto3" json:"sell,omitempty"`
}

func (x *GetSellResponse) Reset() {
	*x = GetSellResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_exchange_rate_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellResponse) ProtoMessage() {}

func (x *GetSellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_exchange_rate_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellResponse.ProtoReflect.Descriptor instead.
func (*GetSellResponse) Descriptor() ([]byte, []int) {
	return file_service_exchange_rate_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetSellResponse) GetSell() float64 {
	if x != nil {
		return x.Sell
	}
	return 0
}

var File_service_exchange_rate_api_proto protoreflect.FileDescriptor

var file_service_exchange_rate_api_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0xe0,
	0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x12, 0x28, 0x0a, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x5f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x75,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x62, 0x75, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x65, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x6c,
	0x12, 0x3f, 0x0a, 0x0d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0c, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74,
	0x65, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x75, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x62, 0x75, 0x79, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x6c, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x6c, 0x32, 0xb1, 0x01, 0x0a,
	0x0f, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x41, 0x50, 0x49,
	0x12, 0x34, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x42, 0x75, 0x79,
	0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x53, 0x65, 0x6c, 0x6c, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x25, 0x5a, 0x23, 0x64, 0x77, 0x69, 0x77, 0x32, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2d, 0x53, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2d,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_exchange_rate_api_proto_rawDescOnce sync.Once
	file_service_exchange_rate_api_proto_rawDescData = file_service_exchange_rate_api_proto_rawDesc
)

func file_service_exchange_rate_api_proto_rawDescGZIP() []byte {
	file_service_exchange_rate_api_proto_rawDescOnce.Do(func() {
		file_service_exchange_rate_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_exchange_rate_api_proto_rawDescData)
	})
	return file_service_exchange_rate_api_proto_rawDescData
}

var file_service_exchange_rate_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_exchange_rate_api_proto_goTypes = []interface{}{
	(*GetRateRequest)(nil),      // 0: pb.GetRateRequest
	(*GetRateResponse)(nil),     // 1: pb.GetRateResponse
	(*GetBuyResponse)(nil),      // 2: pb.GetBuyResponse
	(*GetSellResponse)(nil),     // 3: pb.GetSellResponse
	(*timestamp.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_service_exchange_rate_api_proto_depIdxs = []int32{
	4, // 0: pb.GetRateResponse.validate_date:type_name -> google.protobuf.Timestamp
	0, // 1: pb.ExchangeRateAPI.GetRate:input_type -> pb.GetRateRequest
	0, // 2: pb.ExchangeRateAPI.GetBuy:input_type -> pb.GetRateRequest
	0, // 3: pb.ExchangeRateAPI.GetSell:input_type -> pb.GetRateRequest
	1, // 4: pb.ExchangeRateAPI.GetRate:output_type -> pb.GetRateResponse
	2, // 5: pb.ExchangeRateAPI.GetBuy:output_type -> pb.GetBuyResponse
	3, // 6: pb.ExchangeRateAPI.GetSell:output_type -> pb.GetSellResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_exchange_rate_api_proto_init() }
func file_service_exchange_rate_api_proto_init() {
	if File_service_exchange_rate_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_exchange_rate_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_exchange_rate_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_exchange_rate_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBuyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_exchange_rate_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSellResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_exchange_rate_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_exchange_rate_api_proto_goTypes,
		DependencyIndexes: file_service_exchange_rate_api_proto_depIdxs,
		MessageInfos:      file_service_exchange_rate_api_proto_msgTypes,
	}.Build()
	File_service_exchange_rate_api_proto = out.File
	file_service_exchange_rate_api_proto_rawDesc = nil
	file_service_exchange_rate_api_proto_goTypes = nil
	file_service_exchange_rate_api_proto_depIdxs = nil
}
